// <auto-generated />
namespace Week12HealthDomain2223.S00211628.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class testmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202212151908360_test migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
